using System.Globalization;

namespace VelaShell.Plugin.Sql;

/// <summary>
/// 插件自带的文案表。插件的国际化由自己负责(SDK 只给 <c>context.Host.Locale</c> 与
/// <c>LocaleChanged</c> 事件),因此这些词条随插件走 —— 它们本就是数据库的领域词汇。
/// <para>
/// 只带简体中文与英文两套(与 Redis / S3 插件同口径):宿主支持五种语言,
/// 但插件文案量大且专业词多,缺哪种语言就回落英文,而不是显示一个键名。
/// </para>
/// </summary>
/// <param name="locale">宿主当前语言(如 <c>zh-Hans</c>、<c>en</c>)。</param>
public sealed class Loc(string locale)
{
    private readonly bool _chinese = locale.StartsWith("zh", StringComparison.OrdinalIgnoreCase);

    /// <summary>取一条文案;未收录的键原样返回(方便一眼看出漏了哪条)。</summary>
    /// <param name="key">文案键。</param>
    /// <returns>文案。</returns>
    public string this[string key] =>
        (_chinese ? Chinese : English).TryGetValue(key, out string? value) ? value : key;

    /// <summary>取一条带占位符的文案并格式化。</summary>
    /// <param name="key">文案键。</param>
    /// <param name="args">占位参数。</param>
    /// <returns>格式化后的文案。</returns>
    public string Format(string key, params object?[] args) =>
        string.Format(CultureInfo.CurrentCulture, this[key], args);

    /// <summary>
    /// 全部文案键(两种语言的并集)。<b>供单测用</b>:字典初始化器里出现重复键会在
    /// <b>静态构造时</b>抛 <c>ArgumentException</c> —— 编译期看不出来,而它一炸就是整个插件不可用。
    /// </summary>
    public static IReadOnlyCollection<string> AllKeys => [.. English.Keys.Union(Chinese.Keys, StringComparer.Ordinal)];

    /// <summary>某种语言收录的键(单测比对两套是否齐平)。</summary>
    /// <param name="chinese">true = 中文表,false = 英文表。</param>
    /// <returns>键集合。</returns>
    public static IReadOnlyCollection<string> KeysOf(bool chinese) => chinese ? Chinese.Keys : English.Keys;

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        // ── 连接表单 ──
        ["Sql_Database"] = "Database",
        ["Sql_DatabasePlaceholder"] = "leave empty to list all",
        ["Sql_DatabaseHint"] = "Default database to open. Leave empty and the object tree lists every database you can see.",
        ["Sql_Schema"] = "Schema",
        ["Sql_SchemaHint"] = "Default schema for the object tree.",
        ["Sql_SchemaHintPg"] = "Written to the connection's search_path. This is the only switch that lets metadata queries see a non-public schema.",
        ["Sql_SqliteFile"] = "Database file",
        ["Sql_SqliteFilePlaceholder"] = "C:\\path\\to\\database.db",
        ["Sql_SqliteReadOnlyOpen"] = "Open read-only",
        ["Sql_SqliteReadOnlyOpenHint"] = "Opens the file without creating -wal/-shm side files. Useful for inspecting a database another process owns.",
        ["Sql_OracleServiceName"] = "Service name / SID",
        ["Sql_OracleServiceNameHint"] = "Falls back to the Database field when empty.",
        ["Sql_OracleConnectAs"] = "Connect as",
        ["Sql_OracleConnectAsNormal"] = "Normal",
        ["Sql_Environment"] = "Environment",
        ["Sql_EnvironmentHint"] = "Drives how strict the write guards are. Guards follow the connection, not a global switch.",
        ["Sql_EnvDevelopment"] = "Development",
        ["Sql_EnvStaging"] = "Staging",
        ["Sql_EnvProduction"] = "PRODUCTION",
        ["Sql_ReadOnly"] = "Read-only connection",
        ["Sql_ReadOnlyHint"] = "Writes are refused before they are sent — not by database permissions, so it holds even when you connect as root.",
        ["Sql_ReadOnlyBadge"] = "READ-ONLY",
        ["Sql_Ssl"] = "TLS",
        ["Sql_SslDisabled"] = "Disabled",
        ["Sql_SslPreferred"] = "Preferred",
        ["Sql_SslRequired"] = "Required (no certificate check)",
        ["Sql_SslVerifyCa"] = "Required, verify CA",
        ["Sql_JumpSession"] = "Via SSH tunnel",
        ["Sql_JumpSessionHint"] = "The host builds the local forward before the session opens; this plugin never sees your SSH credentials.",
        ["Sql_MySqlAllowUserVariables"] = "Allow user variables",
        ["Sql_MySqlAllowUserVariablesHint"] = "Off means SET @x := 1 fails with a misleading \"parameter not defined\" error. Leave it on unless you know why not.",
        ["Sql_MySqlZeroDate"] = "Zero dates (0000-00-00)",
        ["Sql_MySqlZeroDateReject"] = "Report an error",
        ["Sql_MySqlZeroDateConvert"] = "Convert to 0001-01-01",
        ["Sql_MySqlZeroDateHint"] = "One zero date makes the whole result set unreadable. Converting makes it readable but shows a value the row does not hold.",
        ["Sql_ConnectTimeout"] = "Connect timeout (s)",
        ["Sql_CommandTimeout"] = "Statement timeout (s)",
        ["Sql_CommandTimeoutHint"] = "Applied to every command. The driver's own connection-string timeout is overridden and has no effect.",

        // ── 连接与错误 ──
        ["Sql_AuthFailed"] = "Authentication failed: {0}",
        ["Sql_ConnectFailed"] = "Cannot reach {0}: {1}",
        ["Sql_ConnectFailedOpaque"] = "Cannot connect to {0}. The driver error code was lost by the SQL layer: {1}",
        ["Sql_DatabaseMissing"] = "The database cannot be opened: {0}",
        ["Sql_DialectNotBundled"] = "{0} needs a driver package that is not bundled with this build.",
        ["Sql_SqliteOpenFailed"] = "Cannot open the SQLite file: {0}",
        ["Sql_Reconnecting"] = "Reconnecting…",

        // ── 面板 ──
        ["Sql_UnknownVersion"] = "(version unavailable)",
        ["Sql_NoDatabaseSelected"] = "(none selected)",
        ["Sql_HandshakeMs"] = "{0} ms",
        ["Sql_ViaTunnel"] = "via {0} → {1}:{2}",
        ["Sql_NodeTables"] = "Tables",
        ["Sql_NodeViews"] = "Views",
        ["Sql_NodeRoutines"] = "Procedures & functions",
        ["Sql_NodeSequences"] = "Sequences",
        ["Sql_NodeSystemObjects"] = "System objects",
        ["Sql_CatalogBadge"] = "in {0}",
        ["Sql_GeneratedColumn"] = "generated",
        ["Sql_FilterObjects"] = "filter objects…",
        ["Sql_QueryTabTitle"] = "Query {0}",
        ["Sql_NothingToRun"] = "Nothing to run.",
        ["Sql_Cancelled"] = "Cancelled.",
        ["Sql_Failed"] = "Failed.",
        ["Sql_Blocked"] = "Refused before sending.",
        ["Sql_BlockedByReadOnly"] = "This connection is marked read-only, so {0} was refused before it was sent. It is not the database's permissions doing this — it holds even when you connect as root.",
        ["Sql_AffectedRows"] = "{0} rows affected · {1} ms",
        ["Sql_BatchDone"] = "{0} statements · {1} ms",
        ["Sql_BatchFailed"] = "Statement {0} of {1} failed. {2}",
        ["Sql_BatchRolledBack"] = "PostgreSQL runs a batch as one implicit transaction, so the earlier statements were rolled back with it.",
        ["Sql_BatchPartiallyCommitted"] = "SQL Server does not roll a batch back: the {0} statements before it are already committed.",
        ["Sql_GridStatus"] = "{0} rows × {1} columns · {2} ms",
        ["Sql_GridStatusTruncated"] = "first {0} rows · {1} ms · more available",
        ["Sql_CellUnreadable"] = "<unreadable: {0}>",
        ["Sql_CellTruncated"] = "truncated; full length {0}",
        ["Sql_ErrorAtLine"] = "line {0}",
        ["Sql_ErrorAtLineColumn"] = "line {0}, column {1}",
        ["Sql_ConfirmTitleYellow"] = "Confirm write",
        ["Sql_ConfirmTitleRed"] = "Dangerous statement",
        ["Sql_ConfirmYellow"] = "{0} on {1} — {2} statement(s) against {3}.",
        ["Sql_ConfirmRed"] = "{0} on {1} — {2} statement(s) against {3}. This is not reversible from here.",
        ["Sql_ConfirmYes"] = "Run",
        ["Sql_ConfirmNo"] = "Cancel",
        ["Sql_CancelStageDriver"] = "cancelling…",
        ["Sql_CancelStageBypass"] = "asking the server directly…",
        ["Sql_CancelStageAbandoned"] = "server did not respond; the connection was abandoned",
        ["Sql_CancelStageDone"] = "cancelled",
        ["Sql_NoBypassCancel"] = "no second connection — cancel cannot escalate",
        ["Sql_GridReadOnlyNoKey"] = "This result set has no primary key or unique index, so a single row cannot be identified — the grid is read-only.",
        ["Sql_GridReadOnlyNotATable"] = "Free-form query results are read-only: there is no single table to write back to.",
        ["Sql_GridReadOnlyKeyNotSelected"] = "The key columns are not in this result set, so a row cannot be identified — the grid is read-only.",
        ["Sql_GridReadOnlyConnection"] = "This connection is marked read-only.",
        ["Sql_NoPendingEdits"] = "Nothing to commit.",
        ["Sql_CommitTitle"] = "Review the SQL before it is sent",
        ["Sql_CommitMessage"] = "{0} statement(s) will be sent:\n\n{1}",
        ["Sql_CommitDone"] = "Committed · {0} rows affected",
        ["Sql_CommitStale"] = "Committed {0} rows, but {1} row(s) matched nothing — someone changed them after you loaded this grid. Reload before retrying.",
        ["Sql_NothingToExport"] = "There is nothing to export yet.",
        ["Sql_NoFilePicker"] = "This build cannot open a save dialog here.",
        ["Sql_Exported"] = "Exported {0} rows to {1}",
        ["Sql_ExportCsv"] = "CSV",
        ["Sql_ExportJson"] = "JSON",
        ["Sql_ExportInsert"] = "INSERT",
        ["Sql_StructureTabTitle"] = "{0} · structure",
        ["Sql_OpsTabTitle"] = "Sessions & locks",
        ["Sql_AutoIncrement"] = "auto",
        ["Sql_StructureLoaded"] = "{0} columns · {1} indexes · {2} foreign keys",
        ["Sql_NoDdlForDialect"] = "{0} does not expose the original CREATE statement.",
        ["Sql_OpsLoaded"] = "{0} sessions · {1} lock waits",
        ["Sql_OpsFailed"] = "Could not read server state: {0}",
        ["Sql_NoOpsForDialect"] = "{0} has no server-side sessions or locks - it runs inside this process.",
        ["Sql_WontKillSelf"] = "That is this window's own session; killing it would only disconnect you.",
        ["Sql_WontKillReadOnly"] = "This connection is marked read-only, so killing another session was refused. Killing a session rolls back its uncommitted work — that is not \"read-only\".",
        ["Sql_Killed"] = "Session {0} was killed.",
        ["Sql_KillFailed"] = "Could not kill session {0}: {1}",
        ["Sql_OpenData"] = "Open data",
        ["Sql_OpenStructure"] = "Show structure",
        ["Sql_OpenOps"] = "Sessions & locks",
        ["Sql_ExplainLabel"] = "Plan",
        ["Sql_ExplainNotSupported"] = "{0} does not provide an execution plan through this client.",
        ["Sql_ExplainAnalyzeRefused"] = "Only the static plan is shown: running the plan would really execute this statement.",
        ["Sql_CommitLabel"] = "Commit edits",
        ["Sql_CommitTooltip"] = "Shows the exact SQL before anything is sent.",
        ["Sql_RevertLabel"] = "Discard edits",
        ["Sql_IndexBackedByConstraint"] = "{0} implements a constraint - DROP INDEX cannot remove it; drop the constraint instead.",
        ["Sql_ExplainEstimateOnly"] = "Every row count here is the optimizer's estimate - this dialect has no run-it-for-real plan.",
        ["Sql_WorkspaceName"] = "Database",
        ["Sql_DialectLabel"] = "Database type",
        ["Sql_DialectHint"] = "Picks the driver, the default port and what the field above means.",
        ["Sql_SchemaPlaceholder"] = "public / dbo",
        ["Sql_SectionEmpty"] = "none",
        ["Sql_ColumnsHeader"] = "Columns",
        ["Sql_IndexesHeader"] = "Indexes",
        ["Sql_ForeignKeysHeader"] = "Foreign keys",
        ["Sql_DdlHeader"] = "CREATE statement",
        ["Sql_KillLabel"] = "Kill session",
        ["Sql_RefreshLabel"] = "Refresh",
        ["Sql_DesignerHeader"] = "Change structure",
        ["Sql_AddColumn"] = "Add column",
        ["Sql_DropColumn"] = "Drop column",
        ["Sql_CreateIndex"] = "Create index",
        ["Sql_DropIndex"] = "Drop index",
        ["Sql_NameRequired"] = "Give it a name first.",
        ["Sql_DdlTitle"] = "Read the DDL before it is sent",
        ["Sql_DdlMessage"] = "This will be sent as-is. DDL does not roll back on most engines:\n\n{0}",
        ["Sql_DdlApplied"] = "Done. The structure was re-read.",
        ["Sql_NoDesignerForDialect"] = "{0} cannot express this change through this client - write the ALTER by hand in a query tab.",
        // ── PG 全文本降级(缺陷 #4)──
        // 用户对着 pg_class 这类系统表点一下就会撞上:relacl 是 aclitem[],服务端没有它的
        // 二进制输出函数,于是整条查询一行都拿不到。执行层用全文本格式重跑救回数据,
        // 代价是所有列都变成字符串 —— 这句话就是把这个代价说给用户听,别让它静默发生。
        ["Sql_TextFallback"] = "PostgreSQL has no binary output for one of these columns (aclitem and its kin only ever had a text form), so this result was fetched again in text mode. Every column now arrives as a string: binary columns read as text instead of 0x…, and the CLR type column says String for everything. The data type names are still the real ones.",
        ["Sql_PanelHint"] = "Browse objects on the left, write SQL above, read results below."
    };

    private static readonly Dictionary<string, string> Chinese = new(StringComparer.Ordinal)
    {
        // ── 连接表单 ──
        ["Sql_Database"] = "数据库",
        ["Sql_DatabasePlaceholder"] = "留空则列出全部",
        ["Sql_DatabaseHint"] = "默认打开的库。留空时对象树列出你能看到的所有库。",
        ["Sql_Schema"] = "Schema",
        ["Sql_SchemaHint"] = "对象树的默认 schema。",
        ["Sql_SchemaHintPg"] = "会写进连接的 search_path。这是元数据查询能看见非 public schema 的唯一开关。",
        ["Sql_SqliteFile"] = "数据库文件",
        ["Sql_SqliteFilePlaceholder"] = "C:\\路径\\数据库.db",
        ["Sql_SqliteReadOnlyOpen"] = "以只读方式打开",
        ["Sql_SqliteReadOnlyOpenHint"] = "不改文件、也不生成 -wal/-shm。适合查看正被别的进程占用的库。",
        ["Sql_OracleServiceName"] = "服务名 / SID",
        ["Sql_OracleServiceNameHint"] = "留空时回落到「数据库」一栏的值。",
        ["Sql_OracleConnectAs"] = "连接身份",
        ["Sql_OracleConnectAsNormal"] = "普通",
        ["Sql_Environment"] = "环境",
        ["Sql_EnvironmentHint"] = "决定写操作护栏的强度。护栏跟着连接走,不是一个全局开关。",
        ["Sql_EnvDevelopment"] = "开发",
        ["Sql_EnvStaging"] = "预发",
        ["Sql_EnvProduction"] = "生产",
        ["Sql_ReadOnly"] = "只读连接",
        ["Sql_ReadOnlyHint"] = "写操作在发出之前就被拒 —— 不靠数据库权限,所以用 root 连也照样拦得住。",
        ["Sql_ReadOnlyBadge"] = "只读",
        ["Sql_Ssl"] = "TLS",
        ["Sql_SslDisabled"] = "不加密",
        ["Sql_SslPreferred"] = "尽量加密",
        ["Sql_SslRequired"] = "必须加密(不校验证书)",
        ["Sql_SslVerifyCa"] = "必须加密并校验 CA",
        ["Sql_JumpSession"] = "经 SSH 隧道",
        ["Sql_JumpSessionHint"] = "宿主在打开会话前代建本地转发;本插件不接触你的 SSH 凭据。",
        ["Sql_MySqlAllowUserVariables"] = "允许用户变量",
        ["Sql_MySqlAllowUserVariablesHint"] = "关掉的话 SET @x := 1 会报错,而且报的是「参数未定义」这种误导消息。没有特别理由就别关。",
        ["Sql_MySqlZeroDate"] = "零日期(0000-00-00)",
        ["Sql_MySqlZeroDateReject"] = "如实报错",
        ["Sql_MySqlZeroDateConvert"] = "转成 0001-01-01",
        ["Sql_MySqlZeroDateHint"] = "表里有一个零日期就会让整张结果集读不出来。转换能读出来,但显示的不是这一行真正的值。",
        ["Sql_ConnectTimeout"] = "连接超时(秒)",
        ["Sql_CommandTimeout"] = "语句超时(秒)",
        ["Sql_CommandTimeoutHint"] = "作用于每一条语句。连接串里的同名设置会被覆盖,配了也不起作用。",

        // ── 连接与错误 ──
        ["Sql_AuthFailed"] = "认证失败:{0}",
        ["Sql_ConnectFailed"] = "连不上 {0}:{1}",
        ["Sql_ConnectFailedOpaque"] = "连不上 {0}。驱动的错误码被 SQL 层吞掉了:{1}",
        ["Sql_DatabaseMissing"] = "打不开这个数据库:{0}",
        ["Sql_DialectNotBundled"] = "{0} 需要本版未内置的驱动包。",
        ["Sql_SqliteOpenFailed"] = "打不开 SQLite 文件:{0}",
        ["Sql_Reconnecting"] = "正在重连…",

        // ── 面板 ──
        ["Sql_UnknownVersion"] = "(拿不到版本)",
        ["Sql_NoDatabaseSelected"] = "(未指定)",
        ["Sql_HandshakeMs"] = "{0} 毫秒",
        ["Sql_ViaTunnel"] = "经 {0} → {1}:{2}",
        ["Sql_NodeTables"] = "表",
        ["Sql_NodeViews"] = "视图",
        ["Sql_NodeRoutines"] = "存储过程与函数",
        ["Sql_NodeSequences"] = "序列",
        ["Sql_NodeSystemObjects"] = "系统对象",
        ["Sql_CatalogBadge"] = "位于 {0}",
        ["Sql_GeneratedColumn"] = "生成列",
        ["Sql_FilterObjects"] = "过滤对象…",
        ["Sql_QueryTabTitle"] = "查询 {0}",
        ["Sql_NothingToRun"] = "没有可执行的语句。",
        ["Sql_Cancelled"] = "已取消。",
        ["Sql_Failed"] = "执行失败。",
        ["Sql_Blocked"] = "已在发出前拒绝。",
        ["Sql_BlockedByReadOnly"] = "这条连接标了只读,所以 {0} 在发出之前就被拒了。拦它的不是数据库权限 —— 用 root 连也照样拦得住。",
        ["Sql_AffectedRows"] = "影响 {0} 行 · {1} 毫秒",
        ["Sql_BatchDone"] = "{0} 条语句 · {1} 毫秒",
        ["Sql_BatchFailed"] = "第 {0} 条(共 {1} 条)失败。{2}",
        ["Sql_BatchRolledBack"] = "PostgreSQL 把一批当一个隐式事务,前面的语句已随它一起回滚。",
        ["Sql_BatchPartiallyCommitted"] = "SQL Server 不会回滚整批:它前面的 {0} 条已经提交了。",
        ["Sql_GridStatus"] = "{0} 行 × {1} 列 · {2} 毫秒",
        ["Sql_GridStatusTruncated"] = "前 {0} 行 · {1} 毫秒 · 还有更多",
        ["Sql_CellUnreadable"] = "<读不出:{0}>",
        ["Sql_CellTruncated"] = "已截断;完整长度 {0}",
        ["Sql_ErrorAtLine"] = "第 {0} 行",
        ["Sql_ErrorAtLineColumn"] = "第 {0} 行第 {1} 列",
        ["Sql_ConfirmTitleYellow"] = "确认写操作",
        ["Sql_ConfirmTitleRed"] = "危险语句",
        ["Sql_ConfirmYellow"] = "将在 {1} 上执行 {0},共 {2} 条语句,目标环境:{3}。",
        ["Sql_ConfirmRed"] = "将在 {1} 上执行 {0},共 {2} 条语句,目标环境:{3}。这一步在这里撤不回来。",
        ["Sql_ConfirmYes"] = "执行",
        ["Sql_ConfirmNo"] = "取消",
        ["Sql_CancelStageDriver"] = "正在取消…",
        ["Sql_CancelStageBypass"] = "正在直接通知服务端…",
        ["Sql_CancelStageAbandoned"] = "服务端未响应取消,已放弃该连接",
        ["Sql_CancelStageDone"] = "已取消",
        ["Sql_NoBypassCancel"] = "没有第二根连接,取消无法升级",
        ["Sql_GridReadOnlyNoKey"] = "这个结果集没有主键也没有唯一索引,定位不到某一行 —— 网格只读。",
        ["Sql_GridReadOnlyNotATable"] = "自由查询的结果只读:我们不知道该往哪张表写回。",
        ["Sql_GridReadOnlyKeyNotSelected"] = "定位用的列不在这个结果集里,定位不到某一行 —— 网格只读。",
        ["Sql_GridReadOnlyConnection"] = "这条连接标了只读。",
        ["Sql_NoPendingEdits"] = "没有待提交的改动。",
        ["Sql_CommitTitle"] = "发出去之前先看一眼 SQL",
        ["Sql_CommitMessage"] = "将发出 {0} 条语句:\n\n{1}",
        ["Sql_CommitDone"] = "已提交 · 影响 {0} 行",
        ["Sql_CommitStale"] = "已提交 {0} 行,但有 {1} 行没匹配上 —— 在你打开网格之后有人改过它们。重新载入再试。",
        ["Sql_NothingToExport"] = "还没有可导出的内容。",
        ["Sql_NoFilePicker"] = "这里打不开保存对话框。",
        ["Sql_Exported"] = "已导出 {0} 行到 {1}",
        ["Sql_ExportCsv"] = "CSV",
        ["Sql_ExportJson"] = "JSON",
        ["Sql_ExportInsert"] = "INSERT",
        ["Sql_StructureTabTitle"] = "{0} · 结构",
        ["Sql_OpsTabTitle"] = "会话与锁",
        ["Sql_AutoIncrement"] = "自增",
        ["Sql_StructureLoaded"] = "{0} 列 · {1} 个索引 · {2} 条外键",
        ["Sql_NoDdlForDialect"] = "{0} 不提供建表语句原文。",
        ["Sql_OpsLoaded"] = "{0} 条会话 · {1} 条锁等待",
        ["Sql_OpsFailed"] = "读不到服务端状态:{0}",
        ["Sql_NoOpsForDialect"] = "{0} 是嵌入式方言,没有服务端会话与锁 —— 它跑在本进程里。",
        ["Sql_WontKillSelf"] = "那是本窗口自己的会话,杀掉只会把你自己断开。",
        ["Sql_WontKillReadOnly"] = "这条连接标着只读,所以杀会话被拒了。杀掉一条会话会把它未提交的事务一并回滚 —— 那不叫\"只读\"。",
        ["Sql_Killed"] = "已杀掉会话 {0}。",
        ["Sql_KillFailed"] = "杀不掉会话 {0}:{1}",
        ["Sql_OpenData"] = "打开数据",
        ["Sql_OpenStructure"] = "查看结构",
        ["Sql_OpenOps"] = "会话与锁",
        ["Sql_ExplainLabel"] = "执行计划",
        ["Sql_ExplainNotSupported"] = "{0} 不通过本客户端提供执行计划。",
        ["Sql_ExplainAnalyzeRefused"] = "只出静态计划:让计划真跑会真的执行这条语句。",
        ["Sql_CommitLabel"] = "提交改动",
        ["Sql_CommitTooltip"] = "发出去之前会先把要执行的 SQL 原样给你看一眼。",
        ["Sql_RevertLabel"] = "撤销改动",
        ["Sql_IndexBackedByConstraint"] = "{0} 是某条约束的实现,DROP INDEX 删不掉它 —— 要删的是那条约束。",
        ["Sql_ExplainEstimateOnly"] = "这里每一个行数都是优化器的估算 —— 这个方言没有「真跑一遍」那一档。",
        ["Sql_WorkspaceName"] = "数据库",
        ["Sql_DialectLabel"] = "数据库类型",
        ["Sql_DialectHint"] = "它决定用哪个驱动、默认端口,以及上面那一栏填的是什么。",
        ["Sql_SchemaPlaceholder"] = "public / dbo",
        ["Sql_SectionEmpty"] = "无",
        ["Sql_ColumnsHeader"] = "列",
        ["Sql_IndexesHeader"] = "索引",
        ["Sql_ForeignKeysHeader"] = "外键",
        ["Sql_DdlHeader"] = "建表语句",
        ["Sql_KillLabel"] = "杀掉会话",
        ["Sql_RefreshLabel"] = "刷新",
        ["Sql_DesignerHeader"] = "改结构",
        ["Sql_AddColumn"] = "加列",
        ["Sql_DropColumn"] = "删列",
        ["Sql_CreateIndex"] = "建索引",
        ["Sql_DropIndex"] = "删索引",
        ["Sql_NameRequired"] = "先起个名字。",
        ["Sql_DdlTitle"] = "发出去之前先看一眼 DDL",
        ["Sql_DdlMessage"] = "下面这条会原样发出去。多数引擎的 DDL 不参与回滚:\n\n{0}",
        ["Sql_DdlApplied"] = "改完了,结构已重读。",
        ["Sql_NoDesignerForDialect"] = "{0} 在本客户端里表达不了这个改动 —— 请在查询页手写 ALTER。",
        // ── PG 全文本降级(缺陷 #4)──
        // 用户对着 pg_class 这类系统表点一下就会撞上:relacl 是 aclitem[],服务端没有它的
        // 二进制输出函数,于是整条查询一行都拿不到。执行层用全文本格式重跑救回数据,
        // 代价是所有列都变成字符串 —— 这句话就是把这个代价说给用户听,别让它静默发生。
        ["Sql_TextFallback"] = "这里有 PostgreSQL 给不出二进制形态的列(aclitem 那一类从来只有文本表示),所以这份结果是用全文本格式重取的。现在每一列都是字符串:二进制列会显示成文本而不是 0x…,CLR 类型那一栏也一律是 String。数据源类型名仍然是真的。",
        ["Sql_PanelHint"] = "左边翻对象,上面写 SQL,下面看结果。"
    };
}
